version: '3'
services:
  redis-server: 
    image: 'redis'
  mongodb-server:
    image: 'mongo'
    ports:
      - "27017:27017"
  node-app:
    image: 'parikshit223933/agrimart'
    ports:
      - "8000:8000"