/* LOGIN */
export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

/* AUTHENTICATING USER ON PAGE REFRESH */
export const AUTHENTICATE_USER='AUTHENTICATE_USER';
export const LOG_OUT='LOG_OUT';

/* Clear AUTH STATE SO THAT WHEN THE USER AGAIN GOES TO SIGN IN PAGE NEXT TIME, HE WONT BE SHOWN AN ERROR */
export const CLEAR_AUTH_STATE='CLEAR_AUTH_STATE';