/* LOGIN */
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/* AUTHENTICATING USER ON PAGE REFRESH */
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";

/* SIGN UP */
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

/* CREATE A NEW PRODUCT */
export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

/* UPDATE USER DETAILS */
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

/* UPLOAD AVATAR */
export const UPLOAD_AVATAR_START = "UPLOAD_AVATAR_START";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAILURE = "UPLOAD_AVATAR_FAILURE";

/* RETRIEVE ALL PRODUCTS BY THE USER */
export const RETRIEVE_PRODUCTS_START = "RETRIEVE_PRODUCTS_START";
export const RETRIEVE_PRODUCTS_FAILURE = "RETRIEVE_PRODUCTS_FAILURE";
export const RETRIEVE_PRODUCTS_SUCCESS = "RETRIEVE_PRODUCTS_SUCCESS";

/* GET ELL THE PRODUCTS THE USER HAS BOUGHT */
export const FETCH_BOUGHT_PRODUCTS_START = "FETCH_BOUGHT_PRODUCTS_START";
export const FETCH_BOUGHT_PRODUCTS_SUCCESS = "FETCH_BOUGHT_PRODUCTS_SUCCESS";
export const FETCH_BOUGHT_PRODUCTS_FAILURE = "FETCH_BOUGHT_PRODUCTS_FAILURE";

/* EDIT A PRODUCT */
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

/* DELETE A PRODUCT */
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

/* GET A SINGLE PRODUCT */
export const GET_SINGLE_PRODUCT_START = "GET_SINGLE_PRODUCT_START";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

/* CREATE A NEW REVIEW */
export const CREATE_REVIEW_START = "CREATE_REVIEW_START";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

/* DELETE A REVIEW */
export const DELETE_REVIEW_START = "DELETE_REVIEW_START";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";

/* UPDATE A REVIEW */
export const UPDATE_REVIEW_START = "UPDATE_REVIEW_START";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAILURE = "UPDATE_REVIEW_FAILURE";

/* TOGGLE A LIKE */
export const TOGGLE_LIKE_START = "TOGGLE_LIKE_START";
export const TOGGLE_LIKE_SUCCESS = "TOGGLE_LIKE_SUCCESS";
export const TOGGLE_LIKE_FAILURE = "TOGGLE_LIKE_FAILURE";

/* TOGGLE A DISLIKE */
export const TOGGLE_DISLIKE_START = "TOGGLE_DISLIKE_START";
export const TOGGLE_DISLIKE_SUCCESS = "TOGGLE_DISLIKE_SUCCESS";
export const TOGGLE_DISLIKE_FAILURE = "TOGGLE_DISLIKE_FAILURE";

/* GET CATEGORIZED PRODUCTS */
export const FETCH_CATEGORIZED_PRODUCTS_START='FETCH_CATEGORIZED_PRODUCTS_START';
export const FETCH_CATEGORIZED_PRODUCTS_SUCCESS='FETCH_CATEGORIZED_PRODUCTS_SUCCESS';
export const FETCH_CATEGORIZED_PRODUCTS_FAILURE='FETCH_CATEGORIZED_PRODUCTS_FAILURE';

/* GET PRODUCTS FROM ALL CATEGORIES FOR HOMEPAGE  */
export const GET_HOME_PRODUCTS_START='GET_HOME_PRODUCTS_START';
export const GET_HOME_PRODUCTS_SUCCESS='GET_HOME_PRODUCTS_SUCCESS';
export const GET_HOME_PRODUCTS_FAILURE='GET_HOME_PRODUCTS_FAILURE';

/* ADD A PRODUCT TO CART */
export const ADD_TO_CART_START='ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS='ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE='ADD_TO_CART_FAILURE';

/* GET ALL CART ITEMS */
export const GET_CART_ITEMS_START='GET_CART_ITEMS_START';
export const GET_CART_ITEMS_SUCCESS='GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAILURE='GET_CART_ITEMS_FAILURE';

/* DECREASE PRODUCT QUANTITY IN THE CART */
export const DECREASE_PRODUCT_QUANTITY_START='DECREASE_PRODUCT_QUANTITY_START';
export const DECREASE_PRODUCT_QUANTITY_SUCCESS='DECREASE_PRODUCT_QUANTITY_SUCCESS';
export const DECREASE_PRODUCT_QUANTITY_FAILURE='DECREASE_PRODUCT_QUANTITY_FAILURE';

/* DELETE RPODUCT FROM CART */
export const DELETE_PRODUCT_FROM_CART_START='DELETE_PRODUCT_FROM_CART_START';
export const DELETE_PRODUCT_FROM_CART_SUCCESS='DELETE_PRODUCT_FROM_CART_SUCCESS';
export const DELETE_PRODUCT_FROM_CART_FAILURE='DELETE_PRODUCT_FROM_CART_FAILURE';

/* CLEARING THE AUTH AND PRODUCT STATE TO SHAOW THE NOTIFICATIONS ACCORDINGLY AND CLEAR THE ERROR STATE */
/* Clear AUTH STATE SO THAT WHEN THE USER AGAIN GOES TO SIGN IN PAGE NEXT TIME, HE WONT BE SHOWN AN ERROR */
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
export const CLEAR_PRODUCT_STATE='CLEAR_PRODUCT_STATE';